### ISSUE TITLE
Question about VATL module

### ISSUE THREAD

**Issue by cj271** [OliverHxh/CAG#1]
Hello, I would like to know when the code will be open-sourced. After reading the paper, I have some questions and hope to clarify them by reading the source code. Or could you help me answer them? My question is, the paper mentions that the Gset in the VATL module is learnable, but I didn’t find how it is learned. It seems to be a hyperparameter?

**Comment by OliverHxh** [comment]
Hi ci271, I planned to open source the code. But recently, I have been occupied by other stuff.  Therefore, it may take some additional time to release the code. 

As for your question about G_{set}, it is initialized as learnable parameters just using nn.Parameter(torch.randn(desired_shape)), which is randomly initialized. 

Feel free to contact me if you have further questions.

Thanks.

**Comment by cj271** [comment]
ok,I got it.Thanks for your reply.
